# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d18031614f077555e63c490cd97a727bc00f3e45a063db498a89308fa636a7d592af31b95ee8ef53ff56b750d08491e0b561264adb0a53e83ef11050a1719f39

test:
  secret_key_base: 6a7ea586cca1f75d31b807e129cce99c237cfc917e9dc15b2eebc38774cda3ae6a0d345e227d4e79a26fc8f72daa907a41a1d92a247a00f2b17f6e5c39aa91df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
